let
	# read a sample .XDSL BN file
	# NOTE: these are generated by Genie / Smile
	#       See Smile.jl
	# Success -> Forecast

	bn = readxdsl(Pkg.dir("BayesNets", "test", "sample_bn.xdsl"))

	@test sort!(names(bn)) == [:Forecast, :Success]
	@test isempty(parents(bn, :Success))
	@test sort!(parents(bn, :Forecast)) == [:Success]

	@test isapprox(pdf(bn, Assignment(:Success=>1, :Forecast=>1)), 0.2*0.4)
	@test isapprox(pdf(bn, Assignment(:Success=>1, :Forecast=>2)), 0.2*0.4)
	@test isapprox(pdf(bn, Assignment(:Success=>1, :Forecast=>3)), 0.2*0.2)
	@test isapprox(pdf(bn, Assignment(:Success=>2, :Forecast=>1)), 0.8*0.1)
	@test isapprox(pdf(bn, Assignment(:Success=>2, :Forecast=>2)), 0.8*0.3)
	@test isapprox(pdf(bn, Assignment(:Success=>2, :Forecast=>3)), 0.8*0.6)
end