let
	# read a sample .XDSL BN file
	# NOTE: these are generated by Genie / Smile
	#       See Smile.jl
	# Success -> Forecast

	bn = readxdsl(Pkg.dir("BayesNets", "test", "sample_bn.xdsl"))

	@test sort!(names(bn)) == [:Forecast, :Success]
	@test isempty(parents(bn, :Success))
	@test sort!(parents(bn, :Forecast)) == [:Success]

	@test isapprox(pdf(bn, :Success=>1, :Forecast=>1), 0.2*0.4)
	@test isapprox(pdf(bn, :Success=>1, :Forecast=>2), 0.2*0.4)
	@test isapprox(pdf(bn, :Success=>1, :Forecast=>3), 0.2*0.2)
	@test isapprox(pdf(bn, :Success=>2, :Forecast=>1), 0.8*0.1)
	@test isapprox(pdf(bn, :Success=>2, :Forecast=>2), 0.8*0.3)
	@test isapprox(pdf(bn, :Success=>2, :Forecast=>3), 0.8*0.6)

    push!(bn, DiscreteCPD(:Test, [:Forecast], [3], [Categorical([1.0, 0.0]),
                                                    Categorical([0.0, 1.0]),
                                                    Categorical([0.1234569, 1-0.1234569])]))

    # test output to text
    filename = tempname()
    open(filename, "w") do io
        write(io, MIME"text/plain"(), bn)
    end

    lines = readlines(filename)
    @test lines[1] == "Success Forecast Test\n"
    @test lines[2] == "010\n"
    @test lines[3] == "001\n"
    @test lines[4] == "000\n"
    @test lines[5] == "2 3 2\n"
    @test lines[6] == "2 4 4 1 3 I 0 123457\n"
    @test length(lines) == 6

    bn2 = open(filename, "r") do io
        read(io, MIME"text/plain"(), DiscreteBayesNet)
    end
    rm(filename)

    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>1, :Test=>1), 0.2*0.4*1.0)
    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>1, :Test=>2), 0.2*0.4*0.0)
    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>2, :Test=>1), 0.2*0.4*0.0)
    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>2, :Test=>2), 0.2*0.4*1.0)
    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>3, :Test=>1), 0.2*0.2*0.123457)
    @test isapprox(pdf(bn2, :Success=>1, :Forecast=>3, :Test=>2), 0.2*0.2*(1-0.123457))
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>1, :Test=>1), 0.8*0.1*1.0)
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>1, :Test=>2), 0.8*0.1*0.0)
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>2, :Test=>1), 0.8*0.3*0.0)
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>2, :Test=>2), 0.8*0.3*1.0)
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>3, :Test=>1), 0.8*0.6*0.123457)
    @test isapprox(pdf(bn2, :Success=>2, :Forecast=>3, :Test=>2), 0.8*0.6*(1-0.123457))

    # plot an empty BayesNet
    # disabled because of latex dependency
    # b = BayesNet()
    # dummy = IOBuffer()
    # show(dummy, MIME("image/svg+xml"), b)
end
